# action.yml
name: 'JSONResume Export'
description: 'Simple GitHub Action to export your JSONResume'
branding:
  icon: 'printer'
  color: 'yellow'
inputs:
  theme:
    description: |
      JSONResume theme name.
      Assumes the theme package would be found 
      as `jsonresume-theme-{theme}` in NPM.
      You can search for themes at https://npmsearch.com/?q=jsonresume-theme
    required: true
    default: 'flat'
  resume_filepath:
    description: |
      File path of the resume in JSONResume format.
    required: false
    default: 'resume.json'
  output_format:
    description: |
      Output file format for exported file - HTML or PDF.
    required: false
    default: 'pdf'
  output_filepath:
    description: |
      Output file path for exported HTML or PDF file.
    required: false
    default: 'resume.pdf'
runs:
  using: 'docker'
  image: 'dumanskiy/action-jsonresume-image:v1'
  args:
    - ${{ inputs.theme }}
    - ${{ inputs.resume_filepath }}
    - ${{ inputs.output_format }}
    - ${{ inputs.output_filepath }}
